
export const CART_FETCH = 'CART_FETCH'

export const CARTS_PRODUCTS_CHANGE = 'CARTS_PRODUCTS_CHANGE'

export const PRODUCT_FETCH ='PRODUCT_FETCH'

export const INPUT_SORT = 'INPUT_SORT'

export const CHANGE_SORT_STATE = 'CHANGE_SORT_STATE'

export const MARK_TYPE_CHANGE = `MARK_TYPE_CHANGE`

export const SELECT_PRODUCT= 'SELECT_PRODUCT'
export const UNSELECT_PRODUCT = 'UNSELECT_PRODUCT'
export const UNSELECT_ALL_PRODUCTS = 'UNSELECT_ALL_PRODUCTS'


export const SELECT_QTY = 'PRODUCT_SELECTION_QTY'

export const HEADER_MODAL_RUN = 'HEADER_MODAL_RUN'

export const ADMIN_INFORMATION_FETCH = 'ADMIN_INFORMATION_FETCH'

export const HISTORY_CHANGING = 'HISTORY_CHANGING'

export const USER_INFORMATION_FETCH = 'USER_INFORMATION_FETCH'

export const EDIT_PRODUCT = 'EDIT_PRODUCT'

export const OPEN_MODAL = 'OPEN_MODAL'

export const REFRESH_STATE = 'REFRESH_STATE'

export const OPEN_PROFILE_EDIT_MODAL = 'OPEN_PROFILE_EDIT_MODAL'

export const SUCCESS_REQUEST = 'SUCCESS_REQUEST'

export const FAILED_REQUEST = 'FAILED_REQUEST'