
export const CART_FETCH = 'CART_FETCH'

export const PRODUCT_FETCH ='PRODUCT_FETCH'

export const INPUT_SORT = 'INPUT_SORT'

export const CHANGE_SORT_STATE = 'CHANGE_SORT_STATE'

export const MARK_TYPE_CHANGE = `MARK_TYPE_CHANGE`

export const PRODUCT_SELECTION_ID = 'PRODUCT_SELECTION_ID'
export const PRODUCT_UNSELECTING_ID = 'PRODUCT_UNSELECTING_ID'
export const UNSELECTING_ALL_ID = 'UNSELECTING_ALL_ID'


export const PRODUCT_SELECTION_QTY = 'PRODUCT_SELECTION_QTY'
